# Generated by Django 2.1.3 on 2018-11-21 03:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referral_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('referral_description', models.CharField(max_length=300)),
                ('ref_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.User')),
                ('referral_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Job.Job')),
            ],
        ),
    ]
