# Generated by Django 2.1.3 on 2018-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_searched_location',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
