# Generated by Django 2.1.3 on 2018-11-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_searched_keyword',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
