# Generated by Django 2.1.3 on 2018-11-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
