# Generated by Django 2.1.3 on 2018-11-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20181122_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_searched_keyword',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
