# Generated by Django 2.1.2 on 2018-11-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default='This company have no descriptions yet.', max_length=300),
        ),
    ]
