# Generated by Django 2.1.2 on 2018-11-14 05:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0002_auto_20181114_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(max_length=150)),
                ('date', models.DateField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('type', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(default='This event have no descriptions yet.', max_length=1000)),
                ('num_views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_favorites', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.Company')),
            ],
        ),
    ]
