# Generated by Django 2.1.3 on 2018-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20181127_2341'),
        ('Event', '0002_event_favorited_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='go_user',
            field=models.ManyToManyField(blank=True, related_name='go', to='User.User'),
        ),
    ]
