# Generated by Django 2.1.3 on 2018-11-03 03:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('F_Name', models.CharField(max_length=20)),
                ('L_Name', models.CharField(max_length=20)),
                ('yr_graduation', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2050, message='Year of graduation should be less than 2050!'), django.core.validators.MinValueValidator(1970, message='Year of graduation should be more than 1970!')])),
                ('contact_email', models.CharField(max_length=60, unique=True, validators=[django.core.validators.EmailValidator(code=None, message='Please Use a valid email address!', whitelist=None)])),
                ('description', models.CharField(max_length=300)),
                ('register_email', models.CharField(max_length=60, unique=True, validators=[django.core.validators.EmailValidator(code=None, message='Please Use a valid email address!', whitelist=None)])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters!')])),
                ('company', models.ManyToManyField(blank=True, to='Company.Company')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.Degree')),
                ('favorite_event', models.ManyToManyField(blank=True, to='Event.Event')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.Major')),
            ],
        ),
    ]
