# Generated by Django 2.1.3 on 2018-12-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_ability',
            field=models.BooleanField(default=False),
        ),
    ]
