# Generated by Django 2.1.3 on 2018-11-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_event',
        ),
    ]
