# Generated by Django 2.1.3 on 2018-11-21 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='yr_graduation',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2050, message='Year of graduation should be less than 2050!'), django.core.validators.MinValueValidator(1970, message='Year of graduation should be more than 1970!')]),
        ),
    ]
