# Generated by Django 2.1.3 on 2018-11-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20181120_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='User.Degree'),
        ),
    ]
