# Generated by Django 2.1.3 on 2018-11-28 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_user_favorite_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=1500, validators=[django.core.validators.MinLengthValidator(50, message='Description must be at least 50 characters!')]),
        ),
    ]
