# Generated by Django 2.1.3 on 2018-11-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20181127_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='from_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_request', to='User.User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='to_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to='User.User'),
        ),
    ]
