# Generated by Django 2.1.4 on 2018-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20181208_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_result',
            field=models.ManyToManyField(blank=True, related_name='result', to='User.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recommended_users',
            field=models.ManyToManyField(blank=True, related_name='recommended', to='User.User'),
        ),
    ]
