# Generated by Django 2.1.3 on 2018-11-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='degree_required',
            field=models.ManyToManyField(blank=True, null=True, to='User.Degree'),
        ),
        migrations.AlterField(
            model_name='job',
            name='major_required',
            field=models.ManyToManyField(blank=True, null=True, to='User.Major'),
        ),
    ]
