# Generated by Django 2.1.3 on 2018-12-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.Job'),
        ),
    ]
