# Generated by Django 2.1.3 on 2018-11-25 07:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Degree_Require',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Major_Require',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_duration',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_end',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_start',
        ),
        migrations.AddField(
            model_name='job',
            name='JobID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_Work_Auth',
            field=models.CharField(choices=[('U.S. Citizens', 'U.S. Citizens Or U.S. Permanent Residents Only'), ('Other', 'All Legal Citizens')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Commission', 'Commission'), ('Internship', 'Internship'), ('Not Available', 'Not Available')], max_length=100),
        ),
    ]
