# Generated by Django 2.1.3 on 2018-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='degree_required',
            field=models.ManyToManyField(blank=True, null=True, to='User.Degree'),
        ),
        migrations.AddField(
            model_name='job',
            name='major_required',
            field=models.ManyToManyField(blank=True, null=True, to='User.Major'),
        ),
    ]
