# Generated by Django 2.1.3 on 2018-11-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_end',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_start',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
