# Generated by Django 2.1.3 on 2018-11-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_auto_20181115_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_end',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_start',
        ),
    ]
