# Generated by Django 2.1.3 on 2018-11-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_auto_20181124_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='ref_provider',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referral_job',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
