# Generated by Django 2.1.3 on 2018-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_auto_20181204_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_Work_Auth',
            field=models.CharField(choices=[('U.S. Citizens', 'U.S. Citizens Or U.S. Permanent Residents Only'), ('Other', 'All Legal Status')], max_length=100),
        ),
    ]
