# Generated by Django 2.1.3 on 2018-11-28 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_auto_20181126_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_views',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
