# Generated by Django 2.1.3 on 2018-12-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_auto_20181205_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_Work_Auth',
            field=models.CharField(choices=[('U.S. Citizens Or U.S. Permanent Residents Only', 'U.S. Citizens Or U.S. Permanent Residents Only'), ('All Legal Status', 'All Legal Status')], max_length=100),
        ),
    ]
